// Accessories Product Data
const accessories = [
    {
        id: 'acc-001',
        name: 'Leather Belt',
        brand: 'LuxeLeather',
        price: 49.99,
        originalPrice: 64.99,
        discount: 23,
        category: 'accessories',
        type: 'belt',
        description: 'Classic leather belt with silver buckle, perfect for formal and casual wear',
        image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=500&fit=crop',
        colors: ['Black', 'Brown', 'Tan'],
        sizes: ['32', '34', '36', '38', '40', '42'],
        rating: 4.6,
        reviews: 287,
        inStock: true,
        tags: ['leather', 'belt', 'classic']
    },
    {
        id: 'acc-002',
        name: 'Wool Knit Beanie',
        brand: 'MANVUE Basics',
        price: 24.99,
        originalPrice: 29.99,
        discount: 17,
        category: 'accessories',
        type: 'hat',
        description: 'Soft wool knit beanie to keep you warm during cold weather',
        image: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=400&h=500&fit=crop',
        colors: ['Black', 'Gray', 'Navy', 'Burgundy', 'Cream'],
        sizes: ['One Size'],
        rating: 4.4,
        reviews: 198,
        inStock: true,
        tags: ['wool', 'beanie', 'winter']
    },
    {
        id: 'acc-003',
        name: 'Cotton Baseball Cap',
        brand: 'MANVUE Basics',
        price: 19.99,
        originalPrice: 24.99,
        discount: 20,
        category: 'accessories',
        type: 'hat',
        description: 'Classic cotton baseball cap with adjustable strap',
        image: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=400&h=500&fit=crop',
        colors: ['Black', 'Navy', 'White', 'Red', 'Gray'],
        sizes: ['One Size'],
        rating: 4.3,
        reviews: 234,
        inStock: true,
        tags: ['cotton', 'baseball', 'cap']
    },
    {
        id: 'acc-004',
        name: 'Silk Tie',
        brand: 'MANVUE Professional',
        price: 39.99,
        originalPrice: 49.99,
        discount: 20,
        category: 'accessories',
        type: 'tie',
        description: 'Elegant silk tie with classic pattern, perfect for business attire',
        image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=500&fit=crop',
        colors: ['Navy Dots', 'Red Stripe', 'Blue Paisley', 'Black Solid'],
        sizes: ['One Size'],
        rating: 4.5,
        reviews: 167,
        inStock: true,
        tags: ['silk', 'tie', 'business']
    },
    {
        id: 'acc-005',
        name: 'Leather Wallet',
        brand: 'LuxeLeather',
        price: 69.99,
        originalPrice: 89.99,
        discount: 22,
        category: 'accessories',
        type: 'wallet',
        description: 'Premium leather bifold wallet with multiple card slots and coin pocket',
        image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=500&fit=crop',
        colors: ['Black', 'Brown', 'Navy'],
        sizes: ['One Size'],
        rating: 4.7,
        reviews: 345,
        inStock: true,
        tags: ['leather', 'wallet', 'bifold']
    },
    {
        id: 'acc-006',
        name: 'Canvas Backpack',
        brand: 'MANVUE Basics',
        price: 79.99,
        originalPrice: 99.99,
        discount: 20,
        category: 'accessories',
        type: 'bag',
        description: 'Durable canvas backpack with laptop compartment and multiple pockets',
        image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=500&fit=crop',
        colors: ['Olive', 'Navy', 'Black', 'Tan'],
        sizes: ['One Size'],
        rating: 4.6,
        reviews: 278,
        inStock: true,
        tags: ['canvas', 'backpack', 'laptop']
    },
    {
        id: 'acc-007',
        name: 'Sunglasses',
        brand: 'MANVUE Basics',
        price: 54.99,
        originalPrice: 69.99,
        discount: 21,
        category: 'accessories',
        type: 'sunglasses',
        description: 'Stylish sunglasses with UV protection and polarized lenses',
        image: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400&h=500&fit=crop',
        colors: ['Black Frame', 'Tortoise', 'Silver', 'Gold'],
        sizes: ['One Size'],
        rating: 4.4,
        reviews: 189,
        inStock: true,
        tags: ['sunglasses', 'UV-protection', 'polarized']
    },
    {
        id: 'acc-008',
        name: 'Wool Scarf',
        brand: 'MANVUE Basics',
        price: 44.99,
        originalPrice: 54.99,
        discount: 18,
        category: 'accessories',
        type: 'scarf',
        description: 'Soft wool scarf perfect for adding warmth and style to any outfit',
        image: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=400&h=500&fit=crop',
        colors: ['Charcoal', 'Navy', 'Burgundy', 'Camel'],
        sizes: ['One Size'],
        rating: 4.5,
        reviews: 156,
        inStock: true,
        tags: ['wool', 'scarf', 'winter']
    },
    {
        id: 'acc-009',
        name: 'Leather Gloves',
        brand: 'LuxeLeather',
        price: 59.99,
        originalPrice: 74.99,
        discount: 20,
        category: 'accessories',
        type: 'gloves',
        description: 'Premium leather gloves with touchscreen compatibility',
        image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=500&fit=crop',
        colors: ['Black', 'Brown'],
        sizes: ['S', 'M', 'L', 'XL'],
        rating: 4.6,
        reviews: 123,
        inStock: true,
        tags: ['leather', 'gloves', 'touchscreen']
    },
    {
        id: 'acc-010',
        name: 'Watch',
        brand: 'MANVUE Professional',
        price: 149.99,
        originalPrice: 199.99,
        discount: 25,
        category: 'accessories',
        type: 'watch',
        description: 'Classic analog watch with stainless steel case and leather strap',
        image: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=400&h=500&fit=crop',
        colors: ['Black Strap', 'Brown Strap', 'Metal Bracelet'],
        sizes: ['One Size'],
        rating: 4.7,
        reviews: 298,
        inStock: true,
        tags: ['watch', 'analog', 'stainless-steel']
    },
    {
        id: 'acc-011',
        name: 'Messenger Bag',
        brand: 'MANVUE Professional',
        price: 89.99,
        originalPrice: 114.99,
        discount: 22,
        category: 'accessories',
        type: 'bag',
        description: 'Professional messenger bag with laptop compartment and adjustable strap',
        image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=500&fit=crop',
        colors: ['Black', 'Brown', 'Navy'],
        sizes: ['One Size'],
        rating: 4.5,
        reviews: 167,
        inStock: true,
        tags: ['messenger', 'professional', 'laptop']
    },
    {
        id: 'acc-012',
        name: 'Pocket Square',
        brand: 'MANVUE Professional',
        price: 19.99,
        originalPrice: 24.99,
        discount: 20,
        category: 'accessories',
        type: 'pocket-square',
        description: 'Elegant silk pocket square to complete your formal look',
        image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=500&fit=crop',
        colors: ['White', 'Navy', 'Burgundy', 'Gray'],
        sizes: ['One Size'],
        rating: 4.4,
        reviews: 89,
        inStock: true,
        tags: ['pocket-square', 'silk', 'formal']
    }
];

export default accessories;
