// Bottoms Product Data
const bottoms = [
    {
        id: 'bottom-001',
        name: 'Classic Straight Jeans',
        brand: 'MANVUE Denim',
        price: 79.99,
        originalPrice: 99.99,
        discount: 20,
        category: 'bottoms',
        type: 'jeans',
        description: 'Classic straight fit jeans in premium denim with comfortable stretch',
        image: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=400&h=500&fit=crop',
        colors: ['Dark Wash', 'Medium Wash', 'Light Wash', 'Black'],
        sizes: ['28', '30', '32', '34', '36', '38'],
        rating: 4.5,
        reviews: 567,
        inStock: true,
        tags: ['straight-fit', 'classic', 'stretch']
    },
    {
        id: 'bottom-002',
        name: 'Slim Fit Chinos',
        brand: 'MANVUE Professional',
        price: 64.99,
        originalPrice: 79.99,
        discount: 19,
        category: 'bottoms',
        type: 'chinos',
        description: 'Smart casual chinos with slim fit and wrinkle-resistant fabric',
        image: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=400&h=500&fit=crop',
        colors: ['Khaki', 'Navy', 'Olive', 'Gray', 'Black'],
        sizes: ['28', '30', '32', '34', '36', '38'],
        rating: 4.6,
        reviews: 423,
        inStock: true,
        tags: ['chinos', 'slim-fit', 'wrinkle-resistant']
    },
    {
        id: 'bottom-003',
        name: 'Athletic Track Pants',
        brand: 'SportMax',
        price: 54.99,
        originalPrice: 67.99,
        discount: 19,
        category: 'bottoms',
        type: 'track-pants',
        description: 'Comfortable track pants with moisture-wicking technology',
        image: 'https://images.unsplash.com/photo-1506629905607-bb91ea4b1c90?w=400&h=500&fit=crop',
        colors: ['Black', 'Navy', 'Gray', 'Dark Green'],
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        rating: 4.4,
        reviews: 298,
        inStock: true,
        tags: ['track-pants', 'athletic', 'moisture-wicking']
    },
    {
        id: 'bottom-004',
        name: 'Cargo Shorts',
        brand: 'MANVUE Basics',
        price: 42.99,
        originalPrice: 52.99,
        discount: 19,
        category: 'bottoms',
        type: 'shorts',
        description: 'Utility cargo shorts with multiple pockets and comfortable fit',
        image: 'https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=400&h=500&fit=crop',
        colors: ['Khaki', 'Olive', 'Navy', 'Black'],
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        rating: 4.3,
        reviews: 234,
        inStock: true,
        tags: ['cargo', 'shorts', 'utility']
    },
    {
        id: 'bottom-005',
        name: 'Skinny Fit Jeans',
        brand: 'MANVUE Denim',
        price: 74.99,
        originalPrice: 94.99,
        discount: 21,
        category: 'bottoms',
        type: 'jeans',
        description: 'Modern skinny fit jeans with premium stretch denim',
        image: 'https://images.unsplash.com/photo-1475178626620-a4d074967452?w=400&h=500&fit=crop',
        colors: ['Black', 'Dark Blue', 'Washed Gray'],
        sizes: ['28', '30', '32', '34', '36'],
        rating: 4.4,
        reviews: 389,
        inStock: true,
        tags: ['skinny-fit', 'stretch', 'modern']
    },
    {
        id: 'bottom-006',
        name: 'Dress Trousers',
        brand: 'MANVUE Professional',
        price: 89.99,
        originalPrice: 114.99,
        discount: 22,
        category: 'bottoms',
        type: 'trousers',
        description: 'Formal dress trousers with flat front and tailored fit',
        image: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=400&h=500&fit=crop',
        colors: ['Black', 'Charcoal', 'Navy', 'Gray'],
        sizes: ['30', '32', '34', '36', '38', '40'],
        rating: 4.7,
        reviews: 267,
        inStock: true,
        tags: ['dress', 'formal', 'tailored']
    },
    {
        id: 'bottom-007',
        name: 'Denim Shorts',
        brand: 'MANVUE Denim',
        price: 36.99,
        originalPrice: 45.99,
        discount: 20,
        category: 'bottoms',
        type: 'shorts',
        description: 'Classic denim shorts with distressed detailing',
        image: 'https://images.unsplash.com/photo-1565084888279-aca607ecce0c?w=400&h=500&fit=crop',
        colors: ['Light Wash', 'Medium Wash', 'Dark Wash'],
        sizes: ['S', 'M', 'L', 'XL'],
        rating: 4.2,
        reviews: 198,
        inStock: true,
        tags: ['denim', 'shorts', 'distressed']
    },
    {
        id: 'bottom-008',
        name: 'Jogger Sweatpants',
        brand: 'SportMax',
        price: 49.99,
        originalPrice: 62.99,
        discount: 21,
        category: 'bottoms',
        type: 'sweatpants',
        description: 'Comfortable jogger sweatpants with tapered fit and elastic waistband',
        image: 'https://images.unsplash.com/photo-1544966503-7cc5ac882d5f?w=400&h=500&fit=crop',
        colors: ['Gray', 'Black', 'Navy', 'Heather Blue'],
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        rating: 4.5,
        reviews: 345,
        inStock: true,
        tags: ['jogger', 'sweatpants', 'comfort']
    },
    {
        id: 'bottom-009',
        name: 'Relaxed Fit Jeans',
        brand: 'MANVUE Denim',
        price: 69.99,
        originalPrice: 87.99,
        discount: 20,
        category: 'bottoms',
        type: 'jeans',
        description: 'Relaxed fit jeans for ultimate comfort and casual style',
        image: 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=400&h=500&fit=crop',
        colors: ['Medium Wash', 'Dark Wash', 'Stone Wash'],
        sizes: ['30', '32', '34', '36', '38', '40'],
        rating: 4.3,
        reviews: 278,
        inStock: true,
        tags: ['relaxed-fit', 'comfort', 'casual']
    },
    {
        id: 'bottom-010',
        name: 'Board Shorts',
        brand: 'SportMax',
        price: 39.99,
        originalPrice: 49.99,
        discount: 20,
        category: 'bottoms',
        type: 'shorts',
        description: 'Quick-dry board shorts perfect for beach and water activities',
        image: 'https://images.unsplash.com/photo-1469259943454-aa100abba749?w=400&h=500&fit=crop',
        colors: ['Navy Wave', 'Tropical Print', 'Black', 'Red'],
        sizes: ['S', 'M', 'L', 'XL'],
        rating: 4.4,
        reviews: 167,
        inStock: true,
        tags: ['board-shorts', 'quick-dry', 'beach']
    },
    {
        id: 'bottom-011',
        name: 'Corduroy Pants',
        brand: 'MANVUE Basics',
        price: 67.99,
        originalPrice: 84.99,
        discount: 20,
        category: 'bottoms',
        type: 'pants',
        description: 'Classic corduroy pants with vintage appeal and modern fit',
        image: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=400&h=500&fit=crop',
        colors: ['Tan', 'Forest Green', 'Navy', 'Burgundy'],
        sizes: ['30', '32', '34', '36', '38'],
        rating: 4.5,
        reviews: 189,
        inStock: true,
        tags: ['corduroy', 'vintage', 'textured']
    },
    {
        id: 'bottom-012',
        name: 'Leather Pants',
        brand: 'LuxeLeather',
        price: 199.99,
        originalPrice: 249.99,
        discount: 20,
        category: 'bottoms',
        type: 'pants',
        description: 'Premium leather pants for edgy and sophisticated looks',
        image: 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=400&h=500&fit=crop',
        colors: ['Black', 'Brown'],
        sizes: ['30', '32', '34', '36'],
        rating: 4.6,
        reviews: 89,
        inStock: true,
        tags: ['leather', 'premium', 'edgy']
    }
];

export default bottoms;
